namespace ishtar.vm.codegen;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

[Generator]
public partial class JMP_Gen : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context) { }

    public void Execute(GeneratorExecutionContext context)
    {
        var sourceBuilder = AddHeader();

        var OCU = "{";
        var CCU = "}";

        sourceBuilder.AppendLine("using System;");
        sourceBuilder.AppendLine($"namespace ishtar.vm.codegen {OCU}");
        sourceBuilder.AppendLine($"public partial class {nameof(JMP_Gen)} {OCU}");
        sourceBuilder.AppendLine("public static void SayHello() { Console.WriteLine(\"foobar\") }");

        sourceBuilder.AppendLine($"{CCU}{CCU}");


        context.AddSource($"{nameof(JMP_Gen)}.generated.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));

    }

    private static StringBuilder AddHeader()
    {
        var sb = new StringBuilder();
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was generated by https://github.com/vein-lang/vein.");
        sb.AppendLine("//");
        sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine("//     the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine();
        return sb;
    }
}
