[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("project_system_test")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("veinc_test")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("veinc")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("rune-cli")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("rune")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("ishtar.generator")]
