<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>scopeName</key>
    <string>source.wave</string>
    <key>uuid</key>
    <string>acd10959-e561-4695-9d2a-c6133f52a163</string>
    <key>fileTypes</key>
    <array>
      <string>wave</string>
    </array>
    <key>name</key>
    <string>Wave Language</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#preprocessor</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#operators</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#numbers</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#storage-types</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#storage-modifier</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#backslash-escapes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#class-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#typdef-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#types</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>declarations</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#type-declarations</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-semicolon</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.line.double-slash.documentation.wave</string>
            <key>begin</key>
            <string>(?:^)(?&gt;\s*)(\/\/[!\/]+)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.documentation.wave</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\n)(?&lt;!\\\n)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#line_continuation_character</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>(\/\*[!*]+(?=\s))(.+)([!*]*\*\/)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.begin.documentation.wave</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.end.documentation.wave</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block.documentation.wave</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.block.documentation.wave</string>
            <key>begin</key>
            <string>((?&gt;\s*)\/\*[!*]+(?:(?:\n|$)|(?=\s)))</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.begin.documentation.wave</string>
              </dict>
            </dict>
            <key>end</key>
            <string>([!*]*\*\/)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.end.documentation.wave</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>^\/\* =(\s*.*?)\s*= \*\/$\n?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.toc-list.banner.block.c</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block.banner.wave</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.block.wave</string>
            <key>begin</key>
            <string>(\/\*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.begin.wave</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\*\/)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.end.wave</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>^\/\/ =(\s*.*?)\s*=$\n?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.toc-list.banner.line.wave</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.line.banner.wave</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>((?:^[ \t]+)?)(?=\/\/)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.wave</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?!\G)</string>
          </dict>
        </array>
      </dict>
      <key>preprocessor</key>
      <dict>
        <key>begin</key>
        <string>^\s*((#)\s*(use|load))\b\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.hash.wave</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=(?://|/\*))|(?&lt;!\\)(?=\n)</string>
        <key>name</key>
        <string>meta.preprocessor.wave</string>
      </dict>
      <key>operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;![\w$])(sizeof)(?![\w$])</string>
            <key>name</key>
            <string>keyword.operator.sizeof.wave</string>
          </dict>
          <dict>
            <key>match</key>
            <string>--</string>
            <key>name</key>
            <string>keyword.operator.decrement.wave</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\+\+</string>
            <key>name</key>
            <string>keyword.operator.increment.wave</string>
          </dict>
          <dict>
            <key>match</key>
            <string>%=|\+=|-=|\*=|(?&lt;!\()/=</string>
            <key>name</key>
            <string>keyword.operator.assignment.compound.wave</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&amp;=|\^=|&lt;&lt;=|&gt;&gt;=|\|=</string>
            <key>name</key>
            <string>keyword.operator.assignment.compound.bitwise.wave</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;&lt;|&gt;&gt;</string>
            <key>name</key>
            <string>keyword.operator.bitwise.shift.wave</string>
          </dict>
          <dict>
            <key>match</key>
            <string>!=|&lt;=|&gt;=|==|&lt;|&gt;</string>
            <key>name</key>
            <string>keyword.operator.comparison.wave</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&amp;&amp;|!|\|\|</string>
            <key>name</key>
            <string>keyword.operator.logical.wave</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&amp;|\||\^|~</string>
            <key>name</key>
            <string>keyword.operator.wave</string>
          </dict>
          <dict>
            <key>match</key>
            <string>=</string>
            <key>name</key>
            <string>keyword.operator.assignment.wave</string>
          </dict>
          <dict>
            <key>match</key>
            <string>%|\*|/|-|\+</string>
            <key>name</key>
            <string>keyword.operator.wave</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.wave</string>
            <key>match</key>
            <string>(?&lt;!\.)\b(nocontrol|global|using|auto|const|if|else|while|do|body|for|is|in|gc|return|fail|operation)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.core.wave</string>
            <key>match</key>
            <string>(?&lt;!\.)\b(struct|record|union)\b</string>
          </dict>
        </array>
      </dict>
      <key>storage-modifier</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>storage.modifier</string>
            <key>match</key>
            <string>\b(gc|new|public|protected|internal|private|static|readonly|const|extern|auto|extensions)\b</string>
          </dict>
        </array>
      </dict>
      <key>class-declaration</key>
      <dict>
        <key>begin</key>
        <string>\b(class)\s+</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.class.wave</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.type.class.wave</string>
            <key>match</key>
            <string>@?[_[:alpha:]][_[:alnum:]]*</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-accessor</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.curlybrace.open.wave</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.curlybrace.close.wave</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#punctuation-semicolon</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>typdef-declaration</key>
      <dict>
        <key>begin</key>
        <string>(\#typedef)\s+</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.typedef.wave</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\=)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.type.class.wave</string>
            <key>match</key>
            <string>@?[_[:alpha:]][_[:alnum:]]*</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-accessor</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.curlybrace.open.wave</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.curlybrace.close.wave</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#punctuation-semicolon</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(byte|float|double|bool|string|void|([ui|i](nt16|nt32|nt64)))\b</string>
            <key>name</key>
            <string>support.type.wave</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b%?(invalid)\b</string>
            <key>name</key>
            <string>invalid.deprecated</string>
          </dict>
        </array>
      </dict>
      <key>punctuation-hash</key>
      <dict>
        <key>name</key>
        <string>punctuation.separator.hash.wave</string>
        <key>match</key>
        <string>#</string>
      </dict>
      <key>punctuation-comma</key>
      <dict>
        <key>name</key>
        <string>punctuation.separator.comma.wave</string>
        <key>match</key>
        <string>,</string>
      </dict>
      <key>punctuation-semicolon</key>
      <dict>
        <key>name</key>
        <string>punctuation.terminator.statement.wave</string>
        <key>match</key>
        <string>;</string>
      </dict>
      <key>punctuation-accessor</key>
      <dict>
        <key>name</key>
        <string>punctuation.accessor.wave</string>
        <key>match</key>
        <string>\.</string>
      </dict>
      <key>type-name</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(@?[_[:alpha:]][_[:alnum:]]*)\s*(\:\:)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.alias.wave</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.coloncolon.wave</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(@?[_[:alpha:]][_[:alnum:]]*)\s*(\.)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.wave</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.accessor.wave</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\.)\s*(@?[_[:alpha:]][_[:alnum:]]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.accessor.wave</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.type.wave</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>storage.type.wave</string>
            <key>match</key>
            <string>@?[_[:alpha:]][_[:alnum:]]*</string>
          </dict>
        </array>
      </dict>
      <key>type-arguments</key>
      <dict>
        <key>begin</key>
        <string>&lt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.typeparameters.begin.wave</string>
          </dict>
        </dict>
        <key>end</key>
        <string>&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.typeparameters.end.wave</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-comma</string>
          </dict>
        </array>
      </dict>
      <key>line_continuation_character</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\\)\n</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.character.escape.line-continuation.wave</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>backslash-escapes</key>
      <dict>
        <key>match</key>
        <string>(?x)\\ (
\\			 |
[abefnprtv'"?]   |
[0-3][0-7]{,2}	 |
[4-7]\d?		|
x[a-fA-F0-9]{,2} |
u[a-fA-F0-9]{,4} |
U[a-fA-F0-9]{,8} )</string>
        <key>name</key>
        <string>constant.character.escape.wave</string>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.wave</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.wave</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.wave</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string_placeholder</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#line_continuation_character</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.wave</string>
              </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.wave</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.wave</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#line_continuation_character</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>